export const pokemonList = [
    { id: 25,  name: "Pikachu",     types: ["Electric"],         weight: "6,0",  height: "0,4", moves: ["Mega-Punch", "Pay-Day"],        description: "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy",                     HP: "035", ATK: "055", DEF: "040", SATK: "050", SDEF: "050", SPD: "090" },
    { id: 1,   name: "Bulbasaur",   types: ["Grass", "Poison"],  weight: "6,9",  height: "0,7", moves: ["Clorophyill", "Overgrow"],      description: "There is a plant seed on its back right from the day this Pokemon is born. The seed slowly grows larger",                   HP: "045", ATK: "049", DEF: "049", SATK: "065", SDEF: "065", SPD: "045" },
    { id: 7,   name: "Squirtle",    types: ["Water"],            weight: "9,0",  height: "0,5", moves: ["Torrent", "Rain-Dish"],         description: "When it retracts its long neck into its shell, it squirts out water with vigorous force.",                                  HP: "044", ATK: "048", DEF: "065", SATK: "050", SDEF: "064", SPD: "043" },
    { id: 4,   name: "Charmander",  types: ["Fire"],             weight: "8,5",  height: "0,6", moves: ["Mega-Puch", "Fire-Punch"],      description: "It has a preference for hot things. When it rains, steam is said to spout from the top of its tail.",                       HP: "039", ATK: "052", DEF: "043", SATK: "060", SDEF: "050", SPD: "065" },
    { id: 12,  name: "Butterfree",  types: ["Bug", "Flying"],    weight: "32,0", height: "1,1", moves: ["Compound-Eyes", "Tinted-Lens"], description: "In battle, it flaps its wings at great speed to release higtly toxic dust into the air.",                                   HP: "060", ATK: "045", DEF: "050", SATK: "090", SDEF: "080", SPD: "070" },
    { id: 304, name: "Aron",        types: ["Steel", "Rock"],    weight: "60,0", height: "0,4", moves: ["Sturdy", "Rock-Head"],          description: "It eats iron ore - and sometimes railroad tracks - to build up the steel armor that protects its body.",                    HP: "050", ATK: "070", DEF: "100", SATK: "040", SDEF: "040", SPD: "030" },
    { id: 132, name: "Ditto",       types: ["Normal"],           weight: "4,0",  height: "0,3", moves: ["Limber", "Imposter"],           description: "It can reconstitute its entire cellular structure to change into what it sees, but it returns to normal when it relaxes.",  HP: "048", ATK: "048", DEF: "048", SATK: "048", SDEF: "048", SPD: "048" },
    { id: 92,  name: "Gastly",      types: ["Ghost", "Type"],    weight: "0,1",  height: "1,3", moves: ["Levitate"],                     description: "Born from gases, anyone would faint if engulled by its gaseous body, which contains poison.",                               HP: "030", ATK: "035", DEF: "030", SATK: "100", SDEF: "035", SPD: "080" },
    { id: 151, name: "Mew",         types: ["Psychic"],          weight: "4,0",  height: "0,4", moves: ["Synchronize"],                  description: "When viewed through a microscope, this Pokémon´s short, fine, delicate hair can be seen.",                                  HP: "100", ATK: "100", DEF: "100", SATK: "100", SDEF: "100", SPD: "100" },
  ];